# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGopherCli < Formula
  desc "A tool to get gopher image!"
  homepage "https://goreleaser.com/borischen0203/go-gopher-cli"
  version "1.1.2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/go-gopher-cli/releases/download/v1.1.2/go-gopher-cli_1.1.2_macOS-64bit.tar.gz"
      sha256 "b2eb79cb41b117cca749b8c4a1d8868e7d50417350171c10212da4d7c082f28b"
    end
    if Hardware::CPU.arm?
      url "https://github.com/borischen0203/go-gopher-cli/releases/download/v1.1.2/go-gopher-cli_1.1.2_macOS-ARM64.tar.gz"
      sha256 "7c099ebf225e80f27a0de711d5831c5ba0558ced1f39a4bea04567fe9b5ee57f"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/go-gopher-cli/releases/download/v1.1.2/go-gopher-cli_1.1.2_Linux-64bit.tar.gz"
      sha256 "355a93a18aeda7c96c82c8438cf185397e6c4aac407eea3d049d022d69cdd52a"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/borischen0203/go-gopher-cli/releases/download/v1.1.2/go-gopher-cli_1.1.2_Linux-ARM64.tar.gz"
      sha256 "16c4d4fe09c6967e40abc5f789faecf09a687b24977d2a27d4beabebedde90f9"
    end
  end

  def install
    bin.install "go-gopher-cli"
  end
end
