# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGopherCli < Formula
  desc "A tool to get gopher image!"
  homepage "https://goreleaser.com/borischen0203/go-gopher-cli"
  version "1.1.3"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/go-gopher-cli/releases/download/v1.1.3/go-gopher-cli_1.1.3_macOS-64bit.tar.gz"
      sha256 "1bb8c0c040791eca933818895f30e91395a30186ac56ef97490595a46d39aa7e"
    end
    if Hardware::CPU.arm?
      url "https://github.com/borischen0203/go-gopher-cli/releases/download/v1.1.3/go-gopher-cli_1.1.3_macOS-ARM64.tar.gz"
      sha256 "a3d2365ff320ef73b733d1e8f2e10a012a4553c25efe5b3b5b29a8610fba53ba"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/go-gopher-cli/releases/download/v1.1.3/go-gopher-cli_1.1.3_Linux-64bit.tar.gz"
      sha256 "24276b862dd84c3126bd755f58a240f6abcfc604b072766032443ca3723b47b3"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/borischen0203/go-gopher-cli/releases/download/v1.1.3/go-gopher-cli_1.1.3_Linux-ARM64.tar.gz"
      sha256 "e9e3490c009888a54ea40bbaa7f6f7664fffd949a6933c1e31239a2d35b51c77"
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  def install
    bin.install "goreleaser"
    bash_completion.install "completions/goreleaser.bash" => "goreleaser"
    zsh_completion.install "completions/goreleaser.zsh" => "_goreleaser"
    fish_completion.install "completions/goreleaser.fish"
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
